ipdb = "/home/millken/qbox_sync/db/ipdb.dat"

[KafkaInput]
topic = "nginxlog"
addrs = ["117.27.249.10:9092","117.27.249.11:9092"]
offset_method = "Newest"

[ElasticSearchOutput]
server = "http://192.168.3.81:9200"
flush_interval = 50
